### ISSUE TITLE
Cannot Add Dataset to Space in Dataset View - Spaces are not found

### ISSUE THREAD

**Issue by tcnichol** [clowder-framework/clowder#274]
**Describe the bug**

If you go to the dataset and try to add it to a space, it seems on develop now no spaces appear. 

The error in the console is this:

```
2021-09-19 13:56:29,212 - [ERROR  ] - application - 

! @7l569je5n - Internal server error, for (GET) [/api/spaces/canEdit?date=5] ->

play.api.Application$$anon$1: Execution exception[[ParseException: Unparseable date: "5"]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.6.jar:2.2.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$13$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:170) [play_2.10-2.2.6.jar:2.2.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$13$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:167) [play_2.10-2.2.6.jar:2.2.6]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library.jar:na]
Caused by: java.text.ParseException: Unparseable date: "5"
	at java.text.DateFormat.parse(DateFormat.java:366) ~[na:1.8.0_131]
	at util.Formatters$.iso8601(Formatters.scala:81) ~[classes/:na]
	at services.mongodb.MongoDBSpaceService.filteredQuery(MongoDBSpaceService.scala:257) ~[classes/:na]
	at services.mongodb.MongoDBSpaceService.list(MongoDBSpaceService.scala:154) ~[classes/:na]
	at services.mongodb.MongoDBSpaceService.listAccess(MongoDBSpaceService.scala:92) ~[classes/:na]
	at api.Spaces.api$Spaces$$listSpaces(Spaces.scala:150) ~[classes/:na]
2021-09-19 14:00:39,072 - [ERROR  ] - application - Error connecting to rabbitmq broker
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_131]
2021-09-19 14:00:39,074 - [ERROR  ] - application - Error connecting to rabbitmq broker
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_131]
2021-09-19 14:00:39,074 - [WARN   ] - application - Could not get bindings
```

Here is what I saw in IntelliJ debug mode:
<img width="1360" alt="Screen Shot 2021-09-19 at 1 56 18 PM" src="https://user-images.githubusercontent.com/40038535/133939636-9c2d7a76-468b-4d1f-92d1-ae7d239437e3.png">

**Comment by lmarini** [comment]
Fixed https://github.com/clowder-framework/clowder/pull/275
