### ISSUE TITLE
Error logging in using CILogon

### ISSUE THREAD

**Issue by robkooper** [clowder-framework/clowder#426]
When using cilogon it will send you to the cilogon page, but then will come back to clowder with an error and you are not logged in.

When looking at the logs it will show a timeout error when trying to get the access token
```
2023-10-13 20:48:31,351 - [ERROR  ] - application - [securesocial] error trying to get an access token for provider cilogon
java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169) ~[com.typesafe.akka.akka-actor_2.10-2.2.0.jar:2.2.0]
	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167) ~[com.typesafe.akka.akka-actor_2.10-2.2.0.jar:2.2.0]
2023-10-13 20:48:31,353 - [ERROR  ] - application - Unable to log user in. An exception was thrown
securesocial.core.AuthenticationException: null
	at securesocial.core.OAuth2Provider.securesocial$core$OAuth2Provider$$getAccessToken(OAuth2Provider.scala:67) ~[ws.securesocial.securesocial_2.10-2.1.4.jar:2.1.4]
	at securesocial.core.OAuth2Provider$$anonfun$3$$anonfun$apply$5$$anonfun$apply$8.apply(OAuth2Provider.scala:106) ~[ws.securesocial.securesocial_2.10-2.1.4.jar:2.1.4]
	at securesocial.core.OAuth2Provider$$anonfun$3$$anonfun$apply$5$$anonfun$apply$8.apply(OAuth2Provider.scala:104) ~[ws.securesocial.securesocial_2.10-2.1.4.jar:2.1.4]
	at scala.Option$WithFilter.map(Option.scala:206) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at securesocial.core.OAuth2Provider$$anonfun$3$$anonfun$apply$5.apply(OAuth2Provider.scala:104) ~[ws.securesocial.securesocial_2.10-2.1.4.jar:2.1.4]
	at securesocial.core.OAuth2Provider$$anonfun$3$$anonfun$apply$5.apply(OAuth2Provider.scala:103) ~[ws.securesocial.securesocial_2.10-2.1.4.jar:2.1.4]
```

We think that this might be related to change on 10/10 of CILogon where they enabled ipv6.

**Comment by robkooper** [comment]
@lmarini and @robkooper  have spoken with the CILogon team and they confirmed they did not see any connections to the service, and we are using the correct ipv4 addresses. We also checked inside the clowder container and it shows that we can connect to the cilogon service. We checked to see if we can set the ip address in the container, but this did not solve the issue.

**Comment by robkooper** [comment]
We have worked with the CILogon team and have identified and resolved this issue. Please create a new issue if you still can not login using CILogon.
